version: "3.2"

services:
  studentclub.api.prod:
    image: registry.gitlab.com/vasin.me/vasin-studentclub-api:latest
    container_name: studentclub.api.prod
    restart: always
    ports:
      - 3000
    environment:
      - NODE_ENV=production
      - MONGO_URI=${STUDENTCLUB_MONGO_URI}
      - MONGO_USER=${STUDENTCLUB_MONGO_USERNAME}
      - MONGO_PASS=${STUDENTCLUB_MONGO_PASSWORD}
      - MONGO_DB=${STUDENTCLUB_MONGO_DATABASE}
      - SECRET=${SECRET}
    volumes:
      - /home/${LINUX_USERNAME}/studentcluub-api-prod/clubs:/clubs
    networks:
      - application-tier

networks:
  application-tier:
