version: "3.2"

services:
  studentclub-api-prod:
    image: registry.gitlab.com/vasin.me/vasin-studentclub-api/production:latest
    container_name: studentclub-api-prod
    restart: always
    ports:
      - 3000
    environment:
      - VIRTUAL_HOST=api.studentclub.vasin.me
      - VIRTUAL_PORT=3000
      - NODE_ENV=production
      - MONGO_URI=${STUDENTCLUB_MONGO_URI}
      - MONGO_USER=${STUDENTCLUB_MONGO_USERNAME}
      - MONGO_PASS=${STUDENTCLUB_MONGO_PASSWORD}
      - MONGO_DB=${STUDENTCLUB_MONGO_DATABASE}
      - SECRET=${SECRET}
    volumes:
      - /home/${LINUX_USERNAME}/studentclub-api-prod/clubs:/clubs
    networks:
      - application-tier

networks:
  application-tier:
